# -*- coding: utf-8 -*-
"""Book Q/A Llama.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HLIfC9bnpDQ5Erh023pOnPznKNNjdUyz
"""

!pip install langchain pypdf unstructured sentence_transformers
!pip install pinecone-client llama-cpp-python huggingface_hub

from langchain.document_loaders import PyPDFLoader, OnlinePDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Pinecone
from sentence_transformers import SentenceTransformer
from langchain.chains.question_answering import load_qa_chain
import pinecone
import os

loader = PyPDFLoader('/content/2. RCNN.pdf')

data = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 500,
                                               chunk_overlap = 0)

docs = text_splitter.split_documents(data)

len(docs)



